#!/usr/bin/env python3
"""Assemble one continuous article from the canonical section files."""
from __future__ import annotations

import json
import re
from pathlib import Path

from project_config import ROOT, load_project

PAPER = ROOT / "docs" / "paper"
MANIFEST = PAPER / "manifest.json"
OUTPUT = ROOT / "docs" / "generated" / "full-article.md"



def rewrite_paper_relative_links(text: str) -> str:
    """Retarget sibling links from docs/paper/ to the generated page."""
    pattern = re.compile(r"(!?\[[^\]]*\]\()([^)]*)(\))")

    def replace(match: re.Match[str]) -> str:
        target = match.group(2).strip()
        if not target:
            return match.group(0)
        # Preserve optional Markdown title after the URL.
        if target.startswith("<") and ">" in target:
            end = target.index(">") + 1
            url = target[1:end - 1]
            suffix = target[end:]
            wrapped = True
        else:
            parts = target.split(maxsplit=1)
            url = parts[0].strip("\"'")
            suffix = " " + parts[1] if len(parts) == 2 else ""
            wrapped = False
        if (
            url.startswith(("http://", "https://", "mailto:", "#", "/", "../"))
            or url.startswith("data:")
        ):
            return match.group(0)
        if url.startswith("./"):
            url = url[2:]
        new_url = "../paper/" + url
        rendered = f"<{new_url}>" if wrapped else new_url
        return match.group(1) + rendered + suffix + match.group(3)

    return pattern.sub(replace, text)

def demote_headings(text: str) -> str:
    """Demote Markdown ATX headings by one level outside fenced code blocks."""
    out: list[str] = []
    in_fence = False
    fence_char = ""
    for line in text.splitlines():
        stripped = line.lstrip()
        if stripped.startswith("```") or stripped.startswith("~~~"):
            marker = stripped[:3]
            if not in_fence:
                in_fence = True
                fence_char = marker
            elif marker == fence_char:
                in_fence = False
                fence_char = ""
            out.append(line)
            continue
        if not in_fence:
            match = re.match(r"^(#{1,5})(\s+.*)$", line)
            if match:
                line = "#" + match.group(1) + match.group(2)
        out.append(line)
    return "\n".join(out).rstrip() + "\n"


def main() -> None:
    project = load_project()
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    sections = manifest["sections"]
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)

    header = f"""<!-- GENERATED FILE: edit docs/paper sections, not this page. -->
# {manifest['title']}

## {manifest['subtitle']}

**{manifest['author']} · {manifest['date']} · artifact v{project['version']}**

!!! info "Single-source generated article"
    This continuous reading view is generated by `scripts/assemble_paper.py`
    from the canonical section files listed in `docs/paper/manifest.json`.
    It is not a second manuscript source. Use the sectional article for stable
    page-level links and review comments.

[Open the sectional article](../paper/index.md){{ .md-button }}
[Open the Lean theorem map](../formalization/index.md){{ .md-button }}

---

"""
    chunks = [header]
    for relative in sections:
        path = PAPER / relative
        chunks.append(demote_headings(rewrite_paper_relative_links(path.read_text(encoding="utf-8"))))
        chunks.append("\n---\n\n")
    content = "".join(chunks).rstrip() + "\n"
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"assembled {len(sections)} article sections -> {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
