name: dependency-review

on:
  pull_request:

permissions:
  contents: read

jobs:
  review:
    runs-on: ubuntu-latest
    if: github.event.repository.visibility == 'public'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
